exports.data = [
    {
        'title': 'test title 1',
        'description': 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost': 249,
        'discountCost': 199,
        'isNew': true,
        'img' : '/img/01.png',
    },
    {
        'title': 'test title 2',
        'description': 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost': 249,
        'discountCost': null,
        'isNew': false,
        'img' : '/img/02.png',
    },
    {
        'title': 'test title 3',
        'description': 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost': 125,
        'isNew': true,
        'discountCost': null,
        'img' : '/img/03.png',
    },
    {
        'title': 'test title 4',
        'description': 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost': 111,
        'discountCost': 90,
        'isNew': false,
        'img' : '/img/04.png',
    },
    {
        'title': 'test title 5',
        'description': 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost': 249,
        'discountCost': null,
        'isNew': true,
        'img' : '/img/05.png',
    },
    {
        'title': 'test title 6',
        'description': 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost': 249,
        'discountCost': null,
        'isNew': true,
        'img' : '/img/06.png',
    },
    {
        'title': 'test title 7',
        'description': 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost': 249,
        'discountCost': null,
        'isNew': false,
        'img' : '/img/07.png',
    },
    {
        'title': 'test title 8',
        'description': 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost': 249,
        'discountCost': null,
        'isNew': false,
        'img' : '/img/08.png',
    },
    {
        'title': 'test title 9',
        'description': 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost': 249,
        'discountCost': null,
        'isNew': false,
        'img' : '/img/01.png',
    },
    {
        'title': 'test title 10',
        'description': 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost': 249,
        'discountCost': 199,
        'isNew': true,
        'img' : '/img/01.png',
    },
    {
        'title': 'test title 12',
        'description': 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost': 249,
        'discountCost': null,
        'isNew': false,
        'img' : '/img/02.png',
    },
    {
        'title': 'test title 13',
        'description': 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost': 125,
        'isNew': true,
        'discountCost': null,
        'img' : '/img/03.png',
    },
    {
        'title': 'test title 14',
        'description': 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost': 111,
        'discountCost': 90,
        'isNew': false,
        'img' : '/img/04.png',
    },
    {
        'title': 'test title 15',
        'description': 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost': 249,
        'discountCost': null,
        'isNew': true,
        'img' : '/img/05.png',
    },
    {
        'title': 'test title 16',
        'description': 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost': 249,
        'discountCost': null,
        'isNew': true,
        'img' : '/img/06.png',
    },
    {
        'title': 'test title 17',
        'description': 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost': 249,
        'discountCost': null,
        'isNew': false,
        'img' : '/img/07.png',
    },
    {
        'title': 'test title 18',
        'description': 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost': 249,
        'discountCost': null,
        'isNew': false,
        'img' : '/img/08.png',
    },
    {
        'title': 'test title 19',
        'description': 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost': 249,
        'discountCost': null,
        'isNew': false,
        'img' : '/img/01.png',
    }
];
